spring:
  application:
    name: zuul
  cloud:
    config:
       override-none: true
#配置rabbitMQ链接信息：
  rabbitmq:
       host: 192.168.80.84
       port: 5672
       username: admin
       password: admin


server:
  port: 7002
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka 
      
      
      
 #配置转发的路由规则：
 #下面的配置是默认的路由规则
 #如果不配置，会从eureka获取注册表，根据注册信息完成自动配置：
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  #开启重试：
  retryable: true
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1 
  
# 配置暴露hystrix监控点：
management:
  endpoints:
    web:
     exposure:
        include: hystrix.stream
